### ISSUE TITLE
README: Link on "Contribution" section is broken

### ISSUE THREAD

**Issue by barbosa** [marcelofabri/xcpretty-json-formatter#1]
It points to https://github.com/marcelofabri/xcpretty-danger-formatter, which doesn't exist.

Is it a future project or you renamed this one and forgot to update that? :smile:

**Comment by marcelofabri** [comment]
Forgot to update :grimacing:

**Comment by marcelofabri** [comment]
Fixed in https://github.com/marcelofabri/xcpretty-json-formatter/commit/fed0761c6a62ae39fa44983af39bc3899bea7deb
