### ISSUE TITLE
Expose test summary information

### ISSUE THREAD

**Issue by valeriomazzeo** [marcelofabri/xcpretty-json-formatter#2]
Great work on this formatter! 👍🏻

It would be great if you could expose also the test summary information:
`Executed 2 tests, with 1 failure (0 unexpected) in 0.266 (0.268) seconds`

Thank you!

**Comment by marcelofabri** [comment]
I'm a bit busy lately. Do you want to give a try? It shouldn't be to hard, since `xcpretty` probably exposes the summary.
