### ISSUE TITLE
rspec format

### ISSUE THREAD

**Issue by djbrooks111** [marcelofabri/xcpretty-json-formatter#6]
I was wondering if there was anyway to use this along side the rspec format for xcpretty. Right now, I am using fastlane's scan with `--formatter 'xcpretty-json-formatter'` and would also like to use `--output_style 'rspec'` which would reduce the amount of output to just warnings/errors/tests. However, when using the two formats together, the errors.json file that this formatter generates is not actually generated.

According to the `rspec.rb` file on xcpretty, there are only five method implemented, none of which exist in this formatter. Therefore, I am wondering if these methods are implemented then both formatters could work together?

**Comment by marcelofabri** [comment]
I don't think xcpretty supports multiple formatters. What you can do is make it a two step process:

```
xcodebuild [flags] | tee xcodebuild.log | xcpretty --output_style 'rspec'
cat xcodebuild.log | xcpretty -f `xcpretty-json-formatter`
```
